[build]
  base    = "website"
  
[[redirects]]
  from = "https://myyopass.netlify.app/*"
  to = "http://s3zvjobipg.execute-api.eu-west-1.amazonaws.com/*"
  force = false
  status = 200
      
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
