[[redirects]]
  from = "/*"
  to = "https://s3zvjobipg.execute-api.eu-west-1.amazonaws.com/yopass/{proxy+}"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
